spring.application.name=stadi

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER PORT (optional)
# ===============================

server.port=8090

# Maximum file size for a single upload
spring.servlet.multipart.max-file-size=110MB
# Maximum request size for multipart/form-data
spring.servlet.multipart.max-request-size=110MB
